statictest fix
sub3er0/gophermart pull request #4
Opened 2024-09-28 16:42 UTC by sub3er0

2024-10-08 02:27 UTC, vokinneberg requested changes
Фух 😓, время летит быстро, и мы уже подобрались к первому выпускному проекту! 🎉 По традиции поздравляю с первым ревью, желаю удачи 🍀 и получить удовольствие от реализации проекта 💪 Хочу отметить сильные стороны твоего PR, а также сделать несколько комментариев по поводу того, на что стоит обратить внимание и что можно улучшить. 🤓

**Сильные стороны твоего PR:**

- Реализация достаточно простая, не перегружена деталями и позволяет легко разобраться в логике 👍
- Реализованный функционал проходит автотесты! ⚡

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

- Было бы здорово реализовать graceful shutdown сервера.
- В конфигурации, мне кажется, что приоритет должен быть у флагов над переменными окружения так как флаги устанавливаются явно.
- Хорошая практика "оборачивать" ошибки, добавляя к ним дополнительный контекст. Это поможет разобраться с тем, в каком месте приложения произошел сбой и с чем он связан, когда ошибка будет залогирована.
- Для авторизации, в принципе достаточно проверить, что используется какой-то один метод передачи данных пользователя - либо AuthHeader, либо Cookie. Это просто два разных способа передать одну и ту же информацию (JWT) и у каждого есть свои недостатки и приемущества.
- Если хочется использовать какое-то значение в качестве отсутствующего значения стоит сделать его именованной константой. Мне так же кажется, что значение по-умолчанию для `int` - `0` больше подходит для индикации того, что пользователя не существует. В то же время название метода `IsUserExists(...)` намекает нам на то, что он должен возвращать `bool`.
    
    Во-вторых обращение к репозиторию через инстанс сервиса `uh.UserService.UserRepository.` не удачная практика. Это с одной стороны ухудшает читаемость, с другой стороны не понятно для чего это нужно и какую проблему мы решаем таким образом. Слои приложения стоит четко разделить и реализовать `IsUserExists` на уровне сервиса (при этом сервис может внутри реализации обращаться к репозиторию с проверкой данных пользователя), либо просто пользоваться инстансом репозитория из хэндлдера.
    
- В таком слое сервисов, который просто проксирует вызовы ко внутреннему экземпляру `OrderRepository`, нет никакого смысла — что изменится, если мы его уберём и будем обращаться напрямую к репозиторию? Думаю, стоит подумать о том, как перенести бизнес-логику из обработчиков на уровень сервисов для того, чтобы сделать их использование оправданным, или вообще избавиться от этого слоя.
- Стоит подумать о том чтобы:
    1. В хэндлере определить интерфейс взаимодействия со слоем сервисов.
    2. Избавиться полностью от вызовов типа `uh.OrderService.OrderRepository.DBStorage`. Все взаимодействие стоит реализовать не через конкретные инстансы сервисов, репозиториев и т.д., а через методы интерфейса. Это поможет изолировать слои друг от друга и работать на уровне абстракций.
    3. Перенести эту логику на уровень слоя сервисов, который и предназначен для того чтобы отделить слой бизнес логики от утилитарного слоя хэндлеров с одной стороны, и утилитарного слоя данных с другой стороны. При таком дизайне получиться, что слой хэндлеров отвечает за работу с запросами и представление данных, слой сервисов отвечает за бизнес-логику, слой репозиториев отвечает за доступ к данынным.
- Не стоит использовать "магические числа" в коде! Если это коды ошибок, стоит сделать их именованными константами. Но я бы рекомендова
- Для обработки заказа не рекомендую использовать технику "fire-and-forget" для запуска опроса accrual и обновление статуса запроса по нескольким причинам:
    1. После выхода из хэндлера ты никак не контролируешь жизненный цикл этой горутины, не можешь ее принудительно завершить или проверить статус ее выполнения.
    2. При большом количестве запросов мы породим не контролируемое количество горутин, которое выполнить неконтролируемое количество запросов к сервису accrual.
    3. Не поддерживается обработка кода `429` от accrual. Что если мы достигли лимита на его стороне и нам надо приостановить все горутины, которые запущены или ограничить количество запросов, которые мы отрпавляем?
    4. Что будет, если мы не получили финальный статус для заказа или горутина отработает с ошибкой? Как завершить обработку заказа?
    5. Что будет, если сервис завершит работу штатно или не штатно и будет перезапущен? Как завершить обработку заказов, которые зависли в промежуточном состоянии?
- Стоит форматировать сообщения об ошибках кронсистентно - либо с прописной, либо с заглавной буквы.
- Вообще хранение и совершение операций с деньгами при помощи типов с плавающей точкой могу вести к неявным ошибкам, так как при математических операциях могу быть неявные округления и т.д., так как это бинарные, а не десятичные типы. Я бы рекомендовал использовать либо то, что называется minimal currency unit (т.е. хранить копейки вместо рублей в целочисленном типе и форматировать их соответствующим образом, когда это необходимо) либо использовать тип `decimal`. Так как в Go нет нативного `decimal` типа, можно использовать сторонние библиотеки.
- Хочу предложить несколько улучшений этого методов репозитрия:
    1. Не стоит возвращать численные коды ошибок, я бы советовал определить собственные ошибки `var ErrOrderDoesNotExsist = errors.New("order does not exist")`, которые можно было бы вернуть и проверить при помощи методов `errors.Is(...)` или `errors.As(...)`. Это намного более идеоматический подход в Go.
    2. Так же можно оборачивать ошибки и добавлять к ним либо дополнительный контекст, либо комбинировать ошибки вместе.
    3. Советую реализовывать методы репозитория так чтобы они выполняли только функцию доступа к данным. Таким образом мы будем соблюдать single responsibility principle - наш репозиторий будет отвечать только за доступ к данным, а бизнес логику по проверке принадлежит ли заказ пользователю я предлагаю перенести на уровень сервиса.
- `_` в Go зарезервировано либо для именования файлов с тестами `*_test.go`, либо для именования файлов, которые связаны с определенной архитектурой `*_amd64.go`. Хотя такого писанного правила и не существует, я бы не рекомендовал использовать `_` для именования других типов файлов. Стоит использовать либо слитное именование `orderrepository.go`, либо camelCase `orderRepository.go`.
- Стоит добавить индексы на поля по которым происходит поиск в БД!

2024-10-08 02:27 UTC, vokinneberg commented on cmd/gophermart/main.go
> +	PgsStorage := &storage.PgStorage{}
Локальные переменные нет смысла именовать с заглавной буквы, напротив стоит именовать из с буквы в нижнем регистре.
```suggestion
	pgsStorage := &storage.PgStorage{}
```

2024-10-08 02:27 UTC, vokinneberg commented on cmd/gophermart/main.go
> +	}
Здесь не совсем понял логику - если `cfg` не `nil`, то выполняем миграции, но не понятно, что будет если `cfg` равно `nil`? Будем запускать приложение без миграций, а как быть с тем, что дальше `cgf` так же используется, и если мы попытаемся обратиться к полю `nil` произойдет паника. Тут стоит реализовать логику более консистентно и возможно завершать приложение, если `cfg == nil`. 
 
```suggestion
	if cfg != nil {
	         return
	}
	
        dsn := cfg.DatabaseDsn
        db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
        
        if err != nil {
	        log.Fatalf("failed to connect database: %v", err)
        }
        
        err = db.AutoMigrate()
        
        if err != nil {
	        log.Fatalf("failed to migrate database: %v", err)
        }
        
        err = db.AutoMigrate(&storage.Order{})
        
        if err != nil {
	        log.Fatalf("failed to migrate database: %v", err)
        }
        
        err = db.AutoMigrate(&storage.User{})
        
        if err != nil {
	        log.Fatalf("failed to migrate database: %v", err)
        }
        
        err = db.AutoMigrate(&storage.UserBalance{})
        
        if err != nil {
	        log.Fatalf("failed to migrate database: %v", err)
        }
        
        err = db.AutoMigrate(&storage.Withdrawal{})
        
        if err != nil {
	        log.Fatalf("failed to migrate database: %v", err)
        }
```

2024-10-08 02:27 UTC, vokinneberg commented on cmd/gophermart/main.go
> +	})
Можно сгруппировать маршруты так чтобы не приходилось дуболирвоать префикс `/api/user`:
```suggestion
	r.Use(middleware.RequestDecompressor)
	r.Route("/api/user", func(r chi.Router) {
		r.Post("/register", userHandler.Register)
		r.Post("/login", userHandler.Login)
		r.With(middleware.TokenAuthMiddleware).Route("/", func(r chi.Router) {
			r.Post("/orders", userHandler.SaveOrder)
			r.Get("/orders", userHandler.GetOrders)
			r.Get("/balance", userHandler.GetBalance)
			r.Post("/balance/withdraw", userHandler.Withdraw)
			r.Get("/withdrawals", userHandler.Withdrawals)
		})
	})
```

2024-10-08 02:27 UTC, vokinneberg commented on cmd/gophermart/main.go
> +	err = http.ListenAndServe(cfg.ServerAddress, r)
Было бы здорово реализовать graceful shutdown сервера.

2024-10-08 02:27 UTC, vokinneberg commented on cmd/gophermart/main.go
> +		dsn := cfg.DatabaseDsn
Возможно стоит вынести такую многословную миграцию в отдельный метод?

2024-10-08 02:27 UTC, vokinneberg commented on internal/config/config.go
> +	cfg := &Config{}
Мне кажется, что приоритет должен быть у флагов над переменными окружения так как флаги устанавливаются явно.

2024-10-08 02:27 UTC, vokinneberg commented on internal/accrual/accrual.go
> +	if resp.StatusCode() != 200 {
Советую заменить "магическое число" на именованую константу из пакета `http`.
```suggestion
	if resp.StatusCode() != http.StatusOK {
```

2024-10-08 02:27 UTC, vokinneberg commented on internal/accrual/accrual.go
> +		return registerResponse, err
Хорошая практика "оборачивать" ошибки, добавляя к ним дополнительный контекст. Это поможет разобраться с тем, в каком месте приложения произошел сбой и с чем он связан, когда ошибка будет залогирована.
```suggestion
		return registerResponse, fmt.Errorf("unexpected status code: %d", resp.StatusCode())
```

2024-10-08 02:27 UTC, vokinneberg commented on internal/middleware/auth.go
> +		if err != nil && authHeader == "" {
В принципе достаточно проверить, что используется какой-то один метод передачи данных пользователя - либо AuthHeader, либо Cookie. Это просто два разных способа передать одну и ту же информацию (JWT) и у каждого есть свои недостатки и приемущества.

2024-10-08 02:27 UTC, vokinneberg commented on internal/handlers/user.go
> +func generateToken(user models.User) (string, error) {
Я бы рекомендовал сгруппировать методы и вспомогательные функции - методы в начале файла, функции в конце.

2024-10-08 02:27 UTC, vokinneberg commented on internal/handlers/user.go
> +type Withdraw struct {
Может быть так же cтоит перенести в пакет `models`?

2024-10-08 02:27 UTC, vokinneberg commented on internal/handlers/user.go
> +	if userID == -2 {
А почему `-2`?   В любом случае, если хочется использовать какое-то значение в качестве отсутствующего значения  стоит сделать его именованной константой. Мне так же кажется, что значение по-умолчанию для `int` - `0` больше подходит для индикации того, что пользователя не существует.  В то же время название метода `IsUserExists(...)` намекает нам на то, что он должен возвращать `bool`. 

Во-вторых обращение к репозиторию через инстанс сервиса `uh.UserService.UserRepository.` не удачная практика. Это с одной стороны ухудшает читаемость, с другой стороны не понятно для чего это нужно и какую проблему мы решаем таким образом. Слои приложения стоит четко разделить и реализовать `IsUserExists` на уровне сервиса (при этом сервис может внутри реализации обращаться к репозиторию с проверкой данных пользователя), либо просто пользоваться инстансом репозитория из хэндлдера.

2024-10-08 02:27 UTC, vokinneberg commented on internal/service/orders.go
> +type OrderService struct {
В таком слое сервисов, который просто проксирует вызовы ко внутреннему экземпляру OrderRepository, нет никакого смысла — что изменится, если мы его уберём и будем обращаться напрямую к репозиторию? Думаю, стоит подумать о том, как перенести бизнес-логику из обработчиков на уровень сервисов для того, чтобы сделать их использование оправданным, или вообще избавиться от этого слоя.

2024-10-08 02:27 UTC, vokinneberg commented on internal/handlers/user.go
> +	}
Стоит подумать о том чтобы:

1. В хэндлере определить интерфейс взаимодействия со слоем сервисов.
2. Избавиться полностью от вызовов типа `uh.OrderService.OrderRepository.DBStorage`. Все взаимодействие стоит реализовать  не через конкретные инстансы сервисов, репозиториев и т.д., а через методы интерфейса. Это поможет изолировать слои друг от друга и работать на уровне абстракций.
3. Перенести эту логику на уровень слоя сервисов, который и предназначен для того чтобы отделить слой бизнес логики от утилитарного слоя хэндлеров с одной стороны, и утилитарного слоя данных с другой стороны.  При таком дизайне получиться, что слой хэндлеров отвечает за работу с запросами и представление данных, слой сервисов отвечает за бизнес-логику, слой репозиториев отвечает за доступ к данынным.

2024-10-08 02:27 UTC, vokinneberg commented on internal/handlers/user.go
> +	authUser, err := uh.UserService.AuthenticateUser(creds.Username, creds.Password)
 Вот собственно то о чем я говорю - ни каких вызовов ко внутренним полям `UserService`. Работа только через интерфейс.

2024-10-08 02:27 UTC, vokinneberg commented on internal/handlers/user.go
> +		http.Error(w, "пользователь не найден", http.StatusNotFound)
Так как мы работаем с маршрутом `/orders`  пользователю может быть не понятно, почему не найден пользователь. Думаю, если запрос прошел авторизацию и попал сюда, но при этом в контексте нет `username` это проблема сервера и возвращать следует код `500 InternalServerError`.

Так же подумал, а зачем нам один дополнительный поиск в БД, если можно сразу в токене хранить `UserID`?

2024-10-08 02:27 UTC, vokinneberg commented on internal/handlers/user.go
> +	}
Мне кажется стоит упорядочить вызовы:
```suggestion
	orderNumber := string(body)
	isDigit := isDigits(orderNumber)
	if !isDigit {
		http.Error(w, "Неверный формат запроса", http.StatusBadRequest)
		return
	}

	if !ValidateNumber(orderNumber) {
		http.Error(w, "Неверный формат номера заказа", http.StatusUnprocessableEntity)
		return
	}

```

2024-10-08 02:27 UTC, vokinneberg commented on internal/handlers/user.go
> +	if result == 1 {
Не стоит использовать "магические числа" в коде! Если это коды ошибок, стоит сделать их именованными константами. Но я бы рекомендовал из сервиса возвращать кастомные ошибки, которые позволили бы проверить их и принять решение.

2024-10-08 02:27 UTC, vokinneberg commented on internal/handlers/user.go
> +	go func() {
Тут не рекомендую использовать технику "fire-and-forget" для запуска опроса accrual и обновление статуса запроса по нескольким причинам:

1. После выхода из хэндлера ты никак не контролируешь жизненный цикл этой горутины, не можешь ее принудительно завершить или проверить статус ее выполнения. 
2. При большом количестве запросов мы породим не контролируемое количество горутин, которое выполнить неконтролируемое количество запросов к сервису accrual.
3. Не поддерживается обработка кода `429` от accrual. Что если мы достигли лимита на его стороне и нам надо приостановить все горутины, которые запущены или ограничить количество запросов, которые мы отрпавляем?  
4. Что будет, если мы не получили финальный статус для заказа или горутина отработает с ошибкой? Как завершить обработку заказа?
5. Что будет, если сервис завершит работу штатно или не штатно и будет перезапущен? Как завершить обработку заказов, которые зависли в промежуточном состоянии?

2024-10-08 02:27 UTC, vokinneberg commented on internal/handlers/user.go
> +	orderData, err := uh.OrderService.GetUserOrders(userID)
По-моему здесь пропустил статус `204 NoContent`, в случае если данных нет.

2024-10-08 02:27 UTC, vokinneberg commented on internal/handlers/user.go
> +		http.Error(w, "пользователь не найден", http.StatusNotFound)
Мне кажется, что стоит форматировать сообщения об ошибках кронсистентно - либо с прописной, либо с заглавной буквы.
```suggestion
		http.Error(w, "Пользователь не найден", http.StatusNotFound)
```

2024-10-08 02:27 UTC, vokinneberg commented on internal/handlers/user.go
> +	withdrawalInfo, err := uh.WithdrawService.Withdrawals(userID)
По-моему здесь пропустил статус `204 NoContent`, в случае если данных нет.

2024-10-08 02:27 UTC, vokinneberg commented on internal/repository/order_repository.go
> +	Current   float32 `json:"current"`
Вообще хранение и совершение операций с деньгами при помощи типов с плавающей точкой могу вести к неявным ошибкам, так как при математических операциях могу быть неявные округления и т.д., так как это бинарные, а не десятичные типы. Я бы рекомендовал использовать либо то, что называется minimal currency unit (т.е. хранить копейки вместо рублей в целочисленном типе и форматировать их соответствующим образом, когда это необходимо) либо использовать тип `decimal`. Так как в Go нет нативного `decimal` типа, можно использовать сторонние библиотеки.

2024-10-08 02:27 UTC, vokinneberg commented on internal/repository/order_repository.go
> +}
Хочу предложить несколько улучшений этого метода репозитрия:

1. Не стоит возвращать численные коды ошибок, я бы советовал определить собственные ошибки `var ErrOrderDoesNotExsist = errors.New("order does not exist")`, которые можно было бы вернуть и проверить при помощи методов `errors.Is(...)` или `errors.As(...)`. Это намного более идеоматический подход в Go. 
2. Так же можно оборачивать ошибки и добавлять к ним либо дополнительный контекст, либо комбинировать ошибки вместе.
3. Мне кажется этот метод реползитория выполняет немного больше работы, чем от него требуется. Я советую просто реализовать метод, который позволяет получать заказ из БД по ID - таким образом мы будем соблюдать single responsibility principle - наш репозиторий будет отвечать только за доступ к данным, а бизнес логику по проверке принадлежит ли заказ пользователю я предлагаю перенести на уровень сервиса.

```suggestion
func (or *OrderRepository) GetOrder(orderNumber string) (*OrderData, error) {
	var order OrderData
	query := "SELECT number, status, accrual, created_at, user_id FROM orders WHERE number = $1"
	err := or.DBStorage.Conn.QueryRow(or.DBStorage.Ctx, query, orderNumber).Scan(&order.Number, &order.Status, &order.Accrual, &order.UploadedAt, &order.UserID)

	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("%w: %s", ErrOrderDoesNotExsist, err)
		}
		return nil, fmt.Errorf("error checking order existence: %w", err)
	}

	return &order, nil
}
```

2024-10-08 02:27 UTC, vokinneberg commented on internal/repository/order_repository.go
> +package repository
`_` в Go зарезервировано либо для именования файлов с тестами `*_test.go`, либо для именования файлов, которые связаны с определенной архитектурой `*_amd64.go`. Хотя такого писанного правила и не существует, я бы не рекомендовал использовать `_` для именования других типов файлов. Стоит использовать либо слитное именование `orderrepository.go`, либо camelCase `orderRepository.go`.

2024-10-08 02:27 UTC, vokinneberg commented on internal/repository/withdraw_repository.go
> +func (wr *WithdrawRepository) Withdraw(userID int, orderNumber string, sum float32) (int, error) {
То же, что я написал выше, касается этого метода - стоит перенести бизнес логику на уровень сервиса.

2024-10-08 02:27 UTC, vokinneberg commented on storage/migrations.go
> +type User struct {
Стоит добавить индексы на поля по которым происходит поиск в БД!

2024-10-08 20:17 UTC, sub3er0 commented on internal/middleware/auth.go
> +		if err != nil && authHeader == "" {
В данном случае такая проверка и производится, ошибка возвращается если оба способа не использованы

2024-10-12 12:54 UTC, sub3er0 commented on internal/handlers/user.go
> +	}
Частично согласен, скрыл все под интерфейсами, но в остальном у меня же в хендлере идет вызов методов разных сервисов. Вроде бы хэндлер не слишком раздут, чтобы скрывать бизнес логику, которая является очередностью вызовов методов сервисов в еще один сервис, но в целом мысль понял.

2024-10-16 03:33 UTC, vokinneberg commented on internal/middleware/auth.go
> +		if err != nil && authHeader == "" {
Странно, но ОК. Видимо разработчики курса перестраховались.

2024-10-16 03:48 UTC, vokinneberg commented on internal/handlers/user.go
> +	}
1. Здесь важно, что таких вот вызовов не должно быть в принципе `uh.OrderService.OrderRepository.DBStorage`, так как в них нет ни какого смысла. Если в хэндлере есть зависимость от `DBStorage` стоит ее добавить.
2. Слой выделяется не исходя из размера, а исходя из зоны ответственности.

2024-10-16 03:52 UTC, vokinneberg approved these changes
Поздравляю, ты справился с первым выпускным проектом! 🎉 Ты реализовал большое количество предложений, которые я сделал на предыдущем ревью, здорово! 👍 Твоё приложение стало лучше, оно функционально и проходит все функциональные тесты. 🚀 

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

- Хочу обратить твое внимание на то, как у тебя реализованы сервисы. В твоей реализации они просто проксируют вызовы к слою доступа к БД и в них как бы нет смысла, потому что логика “размазана” по слою хэндлеров и слою доступа к БД. Это указывает на фундаментальное недопонимание назначения это слоя в дизайне приложения. Стоит обратить на это внимание!
- Так как ты объявил интерфейсы возможно более привычно для других ООП языков программирования, но не типично для Go. Предлагаю в будущем все-таки попробовать следовать рекомендации объявлять интерфейсы там, где они непосредственно используются. Контракт в этом случае определяет клиент и это фундаментальное отличие в Go.
- Твоя реализация обработки заказов в горутине, которая вызывается из хэндлера все еще имеет недостатки. Подумай, как бы ты обработал ситуацию с кодом `429` , который ты можешь получить от accrual, а так же рестарт приложения.
- Стоит добавить индексы на поля по которым происходит поиск в БД!
- В проекте совсем нет тестов. Тестирование это важнейшая часть процесса разработки и я рекомендую взять за правило покрывать тестами свой код.

2024-10-29 19:18 UTC, merged